name: Release-Workflow
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch to checkout when making the release."
        required: true
        default: "master"
#      releaseVersion:
#        description: "Default version to use when preparing a release."
#        required: true
#        default: "X.Y.Z"
#      developmentVersion:
#        description: "Default version to use for new local working copy."
#        required: true
#        default: "X.Y.Z-SNAPSHOT"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout-Source-Code-Step
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set-up-JDK-Step
        uses: actions/setup-java@v1
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Cache-local-Maven-repository-Step
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Configure-Git-User-Step
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Make-Release-Step
        run: mvn release:prepare release:perform -B -s .github/mvn-settings.xml
        # -DreleaseVersion=${{ github.event.inputs.releaseVersion }} -DdevelopmentVersion=${{ github.event.inputs.developmentVersion }}
        env:
          #          CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
          #          CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
